FROM --platform=linux/arm64 golang:1.22.5 AS builder
WORKDIR /app
COPY . .
#RUN GOOS=darwin CGO_ENABLED=0 go build -ldflags="-w -s" -o rate-limit cmd/api/main.go
RUN go mod tidy
RUN GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o rate-limit cmd/api/main.go

FROM --platform=linux/arm64 alpine
EXPOSE 8080
COPY --from=builder /app/rate-limit .
CMD ["./rate-limit"]