version: '3.8'

services:
  app:
    build: ./app
    container_name: go_app
    depends_on:
      - redis
    networks:
      - rate-limit-network

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - rate-limit-network

networks:
  rate-limit-network:
    driver: bridge
