# version: '3.8'

services:
  rate-limit-prd:
    image: rogeriotadim/pos-go-expert:ratelimit
    container_name: rate-limit-prd
    environment:
      RATELIMIT: 10
      RATELIMIT_CLEANUP_INTERVAL: 1000
      RATELIMIT_BLOCK_TIME: 30000
      RATELIMIT_TOKEN_LIST: 20,50,100,200,500
      RATELIMIT_REDIS_URL: redis-prd:6379
    depends_on:
      - redis-prd
    ports:
      - 8080:8080
    networks:
      - rate-limit-network-prd

  redis-prd:
    image: redis:latest
    container_name: redis-prd
    networks:
      - rate-limit-network-prd

  stress-ip:
    image: grafana/k6:latest
    container_name: stress-ip
    environment:
      RATELIMIT_HOST_TARGET: rate-limit-prd
      RATELIMIT_PORT_TARGET: 8080
    command: run --vus 1 --duration 60s --rps 25 /app/k6-script.js
    depends_on:
      - rate-limit-prd
    volumes:
      - ./stress:/app
    networks:
      - rate-limit-network-prd

  stress-token:
    image: grafana/k6:latest
    container_name: stress-token
    environment:
      RATELIMIT_HOST_TARGET: rate-limit-prd
      RATELIMIT_PORT_TARGET: 8080
      RATELIMIT_TOKEN_LIMIT_TARGET: 20
    command: run --vus 1 --duration 60s --rps 25 /app/k6-script-token.js
    depends_on:
      - rate-limit-prd
    volumes:
      - ./stress:/app
    networks:
      - rate-limit-network-prd

networks:
  rate-limit-network-prd:
    driver: bridge
